[package]
name = "fyzx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
circular-queue = "0.2.6"
glam = "0.24.1"
kiss3d = "0.35.0"
rand = "0.8.5"
